name: Jekyll site CI

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
            ${{ runner.os }}-gems-
    - uses: helaili/jekyll-action@2.0.5    # Choose any one of the Jekyll Actions
      with:                                # Some relative inputs of your action
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Move files to 'page' folder
      run: mkdir page && cp -R _site/* page/ && cp CNAME page/ && touch page/.nojekyll && cp -r .well-known page/

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: page # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch

