name: Jekyll site CI

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:3.8 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"

    - name: Build the site in the jekyll/builder container
      run: mkdir page && cp -R _site/* page/ && cp CNAME page/

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop # The branch the action should deploy from.
        BRANCH: master # The branch the action should deploy to.
        FOLDER: page # The folder the action should deploy.
        # BUILD_SCRIPT: mkdir page && mv _site page/
